### ISSUE TITLE
What is more in jenkins-trigger than in jenkins CLI?

### ISSUE THREAD

**Issue by Isammoc** [algorys/jenkins-trigger#2]
Which feature this tool will perform that is not already in : [Jenkins CLI](https://jenkins.io/doc/book/managing/cli/)

**Comment by algorys** [comment]
Nothing more, except that it is in python. 

And personally, I have encountered quite a bit of difficulty to use Jenkins cli, that's why I make this script.

**Comment by Isammoc** [comment]
Maybe it will be interesting to say that on `README.md`? :smiley:

**Comment by algorys** [comment]
Good idea. I've added it.

Can I close issue ?

**Comment by Isammoc** [comment]
Thanks for information
